### ISSUE TITLE
중첩된 Accordion 컴포넌트 디자인 예시

### ISSUE THREAD

**Issue by KimJaeGwan** [niawa/AOA#23]
@yamoo9 님
예시로 보여주신 통일부 메뉴의 경우 [네비게이션 트리뷰](http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2b.html)와 흡사하여 혼돈이 올 수 있을 것 같습니다.
중첩된 Accordion 컴포넌트 디자인 예시를 아래 이미지와 경로로 변경하는 건 어떨지 의견 드립니다.

<img src="https://i0.wp.com/webdesignledger.com/wp-content/uploads/2014/12/gallery-15-responsive-bem-accordion-open-source.jpg?w=970">

https://codepen.io/hamwithglasses/pen/cFokD

**Comment by yamoo9** [comment]
@KimJaeGwan 감사합니다 ^^

국내 사례를 찾다 보니 통일부 예시를 이야기 드렸는데 
말씀하신 것처럼 [Navigation Treeview](http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2b.html)가 보다 적합하네요. ^^;

[BEM Accordion, codepen.io](https://codepen.io/hamwithglasses/pen/cFokD) 링크까지 남겨주시다니! 친절하시네요 👍 
그런데 역시나 헤더에 이벤트를 걸어놔서 접근성은 별도로 반영해야 할 듯 ㅠㅡㅠ

강의 잘 듣고 피드백도 주셔서 너무 감사합니다~
